### ISSUE TITLE
SolidityLexer: >=0.4.23. Only pinned or ^ versions are supported

### ISSUE THREAD

**Issue by JohannesMayerConda** [JoinColony/solidity-steamroller#2]
SolidityLexer.js throws this error and the reason is likely [new syntax](https://solidity.readthedocs.io/en/v0.5.2/050-breaking-changes.html#interoperability-with-older-contracts).

(the error was very "masked", I had to console.log(offendingSymbol) in ErrorListener.js syntaxError function)

It seems this is the solidity-parser-antlr you reference in package.json...

I found this https://github.com/protofire/solhint/issues/84 and this SolidityLexer.js closed issue about this https://github.com/protofire/solhint/blob/master/lib/grammar/SolidityLexer.js file that looks alike

An upgrade of this package might fix it

**Comment by chmanie** [comment]
I can upgrade this package for you and release a new version. Let’s see if it fixes your issue.

**Comment by JohannesMayerConda** [comment]
Thanks for upgrading
